/*数据库配置表*/
/*
CREATE TABLE metadbcfg (
    DBNAME VARCHAR (48),
	CNNAME VARCHAR (96),
	DRIVERCLASSNAME VARCHAR (96),
	url VARCHAR (3072),
	USERNAME VARCHAR (96),
	PASSWORD VARCHAR (192),
	JNDINAME VARCHAR (96),
	ALIAS VARCHAR (192),
	REMARK VARCHAR (192)
); 

/*系统用户配置表*/
CREATE TABLE metauser (
	USERNAME VARCHAR (192),
	USECNNAME VARCHAR (192),
	PASSWORD VARCHAR (192),
	REMARK VARCHAR (96),
	QQ VARCHAR (96),
	MSN VARCHAR (96),
	PHONE VARCHAR (96),
	MAIL VARCHAR (96),
	MD5PASS VARCHAR (192),
	DBUSER VARCHAR (96)
); 

/*系统用户组配置表*/
CREATE TABLE metagroup (
	GROUPCODE VARCHAR (192),
	GROUPNAME VARCHAR (192),
	TYPE VARCHAR (192),
	teamcode VARCHAR (48),
	team_code VARCHAR (96)
); 

/*系统用户组与用户关系配置表*/
CREATE TABLE metagroupuser (
	USERNAME VARCHAR (192),
	GROUPCODE VARCHAR (192),
	USERROLE VARCHAR (96),
	REMARK VARCHAR (192)
); 

/*系统用户组与用户关系配置表*/
CREATE TABLE metamodel (
	MODELCODE VARCHAR (96),
	PARENTCODE VARCHAR (96),
	MODELNAME VARCHAR (192),
	MODELTYPE VARCHAR (96),
	CRETIME DATE ,
	REMARK VARCHAR (360),
	CLASSTYPE VARCHAR (96),
	SEQ INT (10),
	IMAGEINDEX INT (10),
	URL VARCHAR (384),
	FRAME VARCHAR (96),
	COUNTSQL VARCHAR (1500),
	IMAGES VARCHAR (192),
	STATE VARCHAR (96)
);

/*菜单权限配置表*/
CREATE TABLE METAPERMISSION (
	MODELCODE VARCHAR (96),
	GROUPCODE VARCHAR (192),
	MODELNAME VARCHAR (192),
	PARENTCODE VARCHAR (96),
	PERMISSIONLEVEL VARCHAR (192)
); 

/*团队表*/
CREATE TABLE meta_team (
	TEAM_CODE VARCHAR (96),
	TEAM_NAME VARCHAR (192),
	TEAM_TYPE VARCHAR (96),
	START_DATE VARCHAR (60),
	END_DATE VARCHAR (60),
	STATE VARCHAR (24),
	REMARK VARCHAR (768),
	RES_CFG VARCHAR (768)
);

/*操作日志*/
CREATE TABLE visitlist (
  LOGINNAME VARCHAR(16) NOT NULL,
  AREA_ID SMALLINT(6) DEFAULT NULL,
  TRACK_MID VARCHAR(64) DEFAULT NULL,
  TRACK VARCHAR(128) DEFAULT NULL,
  IPADDR VARCHAR(16) DEFAULT NULL,
  URI VARCHAR(128) DEFAULT NULL,
  PARAM VARCHAR(128) DEFAULT NULL,
  OPERTYPE VARCHAR(256) DEFAULT NULL,
  OPERNAME VARCHAR(128) DEFAULT NULL,
  APP_SERV VARCHAR(32) DEFAULT NULL,
  CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DUR_TIME INT(11) DEFAULT NULL,
  UA VARCHAR(16) DEFAULT NULL
) ;

/*程序基本信息*/
/*
CREATE TABLE PROC
(
   XMLID                  VARCHAR(64) NOT NULL,
   PROC_NAME              VARCHAR(64) NOT NULL,
   INTERCODE              VARCHAR(20),
   PROCCNNAME             VARCHAR(120),
   INORFULL               VARCHAR(4),
   CYCLETYPE              VARCHAR(60),
   TOPICNAME              VARCHAR(60),
   STARTDATE              VARCHAR(16),
   STARTTIME              TIME,
   ENDTIME                TIME,
   PARENTPROC             VARCHAR(32),
   REMARK                 VARCHAR(255),
   EFF_DATE               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CREATER                VARCHAR(32),
   STATE                  VARCHAR(32),
   STATE_DATE             DATE,
   PROCTYPE               VARCHAR(32),
   PATH                   VARCHAR(200),
   RUNMODE                VARCHAR(32),
   DBUSER                 VARCHAR(32),
   CURTASKCODE            VARCHAR(32),
   DESIGNER               VARCHAR(32),
   AUDITER                VARCHAR(32),
   DEPLOYER               VARCHAR(32),
   RUNPARA                VARCHAR(300),
   RUNDURA                VARCHAR(32),
   TEAM_CODE              VARCHAR(32),
   DEVELOPER              VARCHAR(32),
   CURDUTYER              VARCHAR(32),
   VERSEQ                 INT(11),
   LEVEL_VAL              VARCHAR(32),
   APPTYPE                VARCHAR(32) COMMENT '应用类型',
   DBNAME                 VARCHAR(32) COMMENT '数据库名',
   EXTEND_CFG             VARCHAR(1024) COMMENT '扩展信息。输入输出表等',
   AREACODE               VARCHAR(16),
   XML                    LONGTEXT,
   PRIMARY KEY (PROC_NAME)
);
*/
/*程序日志*/
CREATE TABLE proc_log (
  PROC_NAME VARCHAR(64) NOT NULL,
  CYCLE_ID DECIMAL(8,0) NOT NULL,
  START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  END_TIME TIMESTAMP NULL DEFAULT NULL,
  DUE_TIME INT(11) DEFAULT NULL,
  EFFECT_ROWS DECIMAL(10,2) DEFAULT NULL,
  RATE DECIMAL(10,2) DEFAULT NULL,
  WRATE INT(11) DEFAULT NULL,
  MRATE INT(11) DEFAULT NULL,
  DQ_RUNSTATE VARCHAR(32) DEFAULT NULL,
  DQ_INTIME VARCHAR(32) DEFAULT NULL,
  DQ_REMARK VARCHAR(64) DEFAULT NULL,
  DQ_STATE VARCHAR(16) DEFAULT NULL,
  REMARK VARCHAR(200) DEFAULT NULL,
  PROC_ID VARCHAR(32) DEFAULT NULL,
  DBMS_ID VARCHAR(32) DEFAULT NULL,
  RESULT INT(11) DEFAULT NULL
);

/*程序步骤信息*/
CREATE TABLE proc_step (
  PROC_NAME VARCHAR(255) NOT NULL,
  STEP_SEQ INT(11) NOT NULL,
  S_STEP INT(11) DEFAULT NULL,
  F_STEP INT(11) DEFAULT NULL,
  N_STEP INT(11) DEFAULT NULL,
  STEP_NAME VARCHAR(256) DEFAULT NULL,
  STEP_TYPE INT(11) DEFAULT NULL,
  STEP_CODE VARCHAR(40) DEFAULT NULL,
  SQL_TEXT MEDIUMTEXT,
  DBNAME VARCHAR(32) DEFAULT NULL,
  AREACODE VARCHAR(6) DEFAULT NULL,
  REMARK VARCHAR(250) DEFAULT NULL,
  PREID VARCHAR(128) DEFAULT NULL,
  AFTID VARCHAR(128) DEFAULT NULL,
  PARNET_ID VARCHAR(8) DEFAULT NULL
);

/*程序步骤日志*/
CREATE TABLE proc_step_log (
  PROC_NAME VARCHAR(255) NOT NULL,
  STEP_SEQ VARCHAR(32) NOT NULL,
  STEP_NAME VARCHAR(64) DEFAULT NULL,
  CYCLE_ID DECIMAL(10,0) NOT NULL,
  START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  END_TIME TIMESTAMP NULL DEFAULT NULL,
  STEP_RESULT VARCHAR(1024) DEFAULT NULL,
  ROWNUM_VAL INT(10) DEFAULT NULL,
  REMARK TEXT,
  SQLCODE VARCHAR(10) DEFAULT NULL,
  PARENTSEQ VARCHAR(32) DEFAULT NULL,
  STEP_TYPE INT(10) DEFAULT NULL,
  SQL_TEXT TEXT,
  AREACODE VARCHAR(10) NOT NULL DEFAULT 'SC',
  REDOTIMES INT(10) DEFAULT NULL,
  RUN_PARAM VARCHAR(1024) DEFAULT NULL,
  BUSIKEY1 VARCHAR(64) DEFAULT NULL,
  BUSIKEY2 VARCHAR(64) DEFAULT NULL,
  BUSIKEY3 VARCHAR(64) DEFAULT NULL
);

/*程序函数信息*/
CREATE TABLE proc_func_def_java (
	FUNC_CODE VARCHAR (288),
	FUNC_ID INT (10),
	FUNC_TYPE VARCHAR (180),
	FUN_ORDSEQ VARCHAR (72),
	FUNC_ICON VARCHAR (288),
	SQL_DEF TEXT ,
	DLL_DEF VARCHAR (2250),
	DLL_FUNC VARCHAR (2250),
	SHELL_NAME VARCHAR (2250),
	MEMO VARCHAR (1800),
	FUNC_NAME VARCHAR (1800),
	APPLY VARCHAR (576),
	REMARK VARCHAR (1152),
	SKIP_FLAG VARCHAR (36),
	CFGJSON TEXT 
); 

/*程序函数参数信息*/
CREATE TABLE proc_func_def_para (
	FUNC_CODE VARCHAR (360),
	PARA_IN_OUT VARCHAR (120),
	PARA_NAME VARCHAR (240),
	PARA_CNNAME VARCHAR (360),
	INPUTTYPE VARCHAR (96),
	INPUTPARA VARCHAR (6000),
	`ISNULL` VARCHAR (6),
	SELVAL VARCHAR (96),
	SELMODEL VARCHAR (96),
	PARA_SEQ INT (11),
	REMARK VARCHAR (1536),
	TABSHEET VARCHAR (384),
	INPUT_STYLE VARCHAR (768),
	DEPENDENCIES VARCHAR (768),
	CHECKITEMS VARCHAR (768)
);*/
