/*数据库配置表*/
/*
insert into metadbcfg (DBNAME, CNNAME, DRIVERCLASSNAME, url, USERNAME, PASSWORD, JNDINAME, ALIAS, REMARK) values('METADB','元数据库','com.mysql.jdbc.Driver','jdbc:mysql://localhost:3306/taskdb','root','NfeoEO5MY6s=','java:comp/env/jdbc/METADB',NULL,NULL);
insert into metadbcfg (DBNAME, CNNAME, DRIVERCLASSNAME, url, USERNAME, PASSWORD, JNDINAME, ALIAS, REMARK) values('METADBS','元数据库','com.mysql.jdbc.Driver','jdbc:mysql://localhost:3306/taskdb','root','NfeoEO5MY6s=','java:comp/env/jdbc/METADB',NULL,NULL);

/*系统菜单配置*/
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr',NULL,'系统管理',NULL,NULL,NULL,NULL,'12',NULL,'','desktop',NULL,NULL,'task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_database','sysmgr','数据库列表',NULL,NULL,NULL,NULL,'6',NULL,'ftl/me/sysmgr/sysmgr_database',NULL,NULL,'fa fa-list-alt text-warning-lter','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_menu','sysmgr','系统菜单配置',NULL,NULL,NULL,NULL,'1',NULL,'ftl/me/sysmgr/sysmgr_menu',NULL,NULL,'fa fa-puzzle-piece text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_user','sysmgr','系统用户配置',NULL,NULL,NULL,NULL,'2',NULL,'ftl/me/sysmgr/sysmgr_user',NULL,NULL,'fa fa-user text-info','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_role','sysmgr','系统角色配置',NULL,NULL,NULL,NULL,'3',NULL,'ftl/me/sysmgr/sysmgr_role',NULL,NULL,'fa fa-users text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_priority','sysmgr','系统权限配置',NULL,NULL,NULL,NULL,'4',NULL,'ftl/me/sysmgr/sysmgr_priority',NULL,NULL,'fa fa-users text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_chang_pwd','sysmgr','修改密码',NULL,NULL,NULL,NULL,'7',NULL,'ftl/me/sysmgr/sysmgr_chang_pwd',NULL,NULL,'fa fa-eye text-warning-dk','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_pwdserv','sysmgr','系统密码服务',NULL,NULL,NULL,NULL,'5',NULL,'ftl/me/sysmgr/sysmgr_pwdserv',NULL,NULL,'fa fa-eye-slash text-primary','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg',NULL,'调度配置',NULL,NULL,NULL,NULL,'2',NULL,'','desktop',NULL,NULL,'task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg_02','task_cfg','任务配置',NULL,NULL,NULL,NULL,'2',NULL,'ftl/task/miniProcList?team_code={team_code}',NULL,NULL,'fa fa-user text-info','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg_03','task_cfg','数据模型',NULL,NULL,NULL,NULL,'3',NULL,'task/model_table',NULL,NULL,'fa fa-users text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg_04','task_cfg','数据字典',NULL,NULL,NULL,NULL,'4',NULL,'ftl/task/model_dictionary',NULL,NULL,'fa fa-users text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg_05','task_cfg','Agent配置',NULL,NULL,NULL,NULL,'5',NULL,'ftl/task/agentList',NULL,NULL,'fa fa-eye text-warning-dk','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_cfg_06','task_cfg','日志周期管理',NULL,NULL,NULL,NULL,'6',NULL,'ftl/task/sysmgr_pwdserv',NULL,NULL,'fa fa-eye-slash text-primary','off');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_monitor',NULL,'调度监控',NULL,NULL,NULL,NULL,'1',NULL,'','desktop',NULL,NULL,'task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_monitor_01','task_monitor','任务监控',NULL,NULL,NULL,NULL,'1',NULL,'task/taskMonitor',NULL,NULL,'fa fa-puzzle-piece text-success','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_monitor_02','task_monitor','Agent监控',NULL,NULL,NULL,NULL,'2',NULL,'ftl/task/agentMonitor',NULL,NULL,'fa fa-user text-info','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_monitor_03','task_monitor','手工任务',NULL,NULL,NULL,NULL,'3',NULL,'ftl/task/scheduleManual',NULL,NULL,'fa fa-user text-info','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('task_monitor_11','task_monitor','数据监控',NULL,NULL,NULL,NULL,'3',NULL,'ftl/task/dataMonitor',NULL,NULL,'fa fa-user text-info','task');
insert into `metamodel` (`MODELCODE`, `PARENTCODE`, `MODELNAME`, `MODELTYPE`, `CRETIME`, `REMARK`, `CLASSTYPE`, `SEQ`, `IMAGEINDEX`, `URL`, `FRAME`, `COUNTSQL`, `IMAGES`, `STATE`) values('sysmgr_host_list','sysmgr','主机配置',NULL,NULL,NULL,'TFMoniteShow','6','1','ftl/task/miniHostList','content',NULL,'fa fa-list-alt','task');
*/



